name: Build and deploy Python project to Azure Function App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' 
  PYTHON_VERSION: '3.13' # Version stable recommandée

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BD93911AFFC4437DB0F49F8D0BF6E2AB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BC4CEBBF9D424FEC93F7FFF251E34D10 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_20C49E96FAD744AD89FAB1A2CFF9AE14 }}

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'tp6appfunction'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          # SCM_DO_BUILD_DURING_DEPLOYMENT dit à Azure de compiler lui-même le requirements.txt
          scm-do-build-during-deployment: true
          enable-oryx-build: true
